[build]
  # Build command - we don't need a build for static files
  command = "echo 'No build needed for static site'"
  # Output directory
  publish = "."

[build.environment]
  # Node version
  NODE_VERSION = "18.17.0"

# Environment variables (you can also set these in Netlify Dashboard)
[context.production.environment]
  SUPABASE_URL = "https://mpolescjssadjshuygwj.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wb2xlc2Nqc3NhZGpzaHV5Z3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODg2MTcsImV4cCI6MjA2MzY2NDYxN30.k1gRYfxHvOTYe8SUl08vLkqn4jpOeC0r5qfR68s2vtA"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Cache static assets
[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "/scripts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Ensure proper MIME types
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=UTF-8"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=UTF-8" 